site_name: Syracuse library documentation

theme:
    name: "material"

plugins:
    - mkdocstrings:
        handlers:
            python:
                options:
                    members_order: "source"
                    show_source: False

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - admonition
    - tables

nav:
    - Syracuse library documentation: index.md
